add readme and make sphinx documentation build
neurodata/brainlit pull request #161
Opened 2020-11-02 20:08 UTC by bvarjavand

2020-11-02 20:22 UTC, tathey1 requested changes
A couple initial comments

- right below the graphic, there is a list of links that don't take me anywhere when I click them 
- typo in brainlit/algorithms/regression "clasifiers"
- Can we have text wrapping on this [page](https://brainlight.readthedocs.io/en/documentation/notebooks/utils/utils.html)? 
- Some random pound symbols [here](https://brainlight.readthedocs.io/en/documentation/notebooks/utils/utils.html#Converting-swc-data-to-neuroglancer-precomputed)
- typo of the word "Algorithms" [here](https://brainlight.readthedocs.io/en/documentation/tutorial.html#algortihms)

I'll add more comments as I see them

2020-11-02 20:30 UTC, bvarjavand commented
In order to make the documentation more accessible, add a short paragraph and a link to a "new to brainlit? getting started" tutorial notebook and the top of home.

2020-11-09 21:13 UTC, tathey1 submitted a review, later dismissed

2020-11-16 21:06 UTC, tathey1 approved these changes

2020-11-16 21:06 UTC, merged