issue #346 + #326
neurodata/brainlit pull request #359
Opened 2022-06-07 21:13 UTC by sejalsrivastava1

Fixed #346 and #326.
 
Added default verbose=True arg to removeSmallCCs method in image_process.py.

Added type annotations to all .py files in algorithms, feature_extraction, napari_viterbrain, utils, viz, and preprocessing.

2022-06-10 14:44 UTC, tathey1 requested changes
added some comments. lastly, i know you referenced the issues in the PR title, but can you link them and also add brief text summarizing what you did in the PR description? also, what do you mean by "commented some minor issues"?

2022-06-10 14:44 UTC, tathey1 commented on brainlit/algorithms/trace_analysis/fit_spline.py
> +# sejalsrivastava1 added type annotations
any reason why we should keep these comments?

2022-06-10 14:44 UTC, tathey1 commented on brainlit/algorithms/trace_analysis/fit_spline.py
> +import pandas
let's do `import pandas as pd` (which we do elsewhere in the package)

2022-06-10 14:44 UTC, tathey1 commented on brainlit/algorithms/trace_analysis/fit_spline.py
> +import pandas
then you'll need to change calls to pandas as pd (e.g. line 34)

2022-06-10 14:44 UTC, tathey1 commented on brainlit/feature_extraction/base.py
> +# sejalsrivastava1 added type annotations
shoould we remove?

2022-06-10 14:44 UTC, tathey1 commented on brainlit/feature_extraction/base.py
> +    ) -> None:
I've never seen return type None (I assumed you just wouldn't put a return type), I'm intrigued by the idea though - any reason why you put this here? Have you seen it before?

2022-06-10 14:44 UTC, tathey1 commented on brainlit/napari_viterbrain/viterbrain_plugin.py
> +# sejalsrivastava1 added type annotations
remove?

2022-06-10 14:44 UTC, tathey1 commented on brainlit/preprocessing/image_process.py
> +def removeSmallCCs(
can you please add verbose=False to this line: https://github.com/neurodata/brainlit/blob/704a0cc439e580fc6b3d4e5aa0812f20be6a67d6/brainlit/algorithms/generate_fragments/state_generation.py#L214

2022-06-10 14:44 UTC, tathey1 commented on brainlit/algorithms/trace_analysis/fit_spline.py
> +# sejalsrivastava1 added type annotations
i'm leaning towards removing them (they are on several files). GitHub automatically keeps track of authors of different files, so I am not sure that adding these author comments are necessary. what do youo think?

2022-06-10 16:30 UTC, sejalsrivastava1 commented on brainlit/algorithms/trace_analysis/fit_spline.py
> +# sejalsrivastava1 added type annotations
yep, I'll be removing them now -- they were mostly just for me to see while i worked in my own environment!

2022-06-10 16:31 UTC, sejalsrivastava1 commented on brainlit/feature_extraction/base.py
> +    ) -> None:
I think I saw it somewhere else in the code and copied it to keep consistency, but I can remove if it's unnecessary.

2022-06-10 16:34 UTC, sejalsrivastava1 commented on brainlit/algorithms/trace_analysis/fit_spline.py
> +# sejalsrivastava1 added type annotations
I think the issues are linked but I'll add them in the description. Also, I think I was just referencing comments I added asking if I should import some packages (ex. pandas) where they were needed, but I ended up just doing it and removing the comments.

2022-06-10 16:44 UTC, sejalsrivastava1 commented on brainlit/feature_extraction/base.py
> +    ) -> None:
https://github.com/neurodata/brainlit/blob/46ecbd5c9a6fddd3fdf3622683a63a674caf43a0/brainlit/algorithms/connect_fragments/viterbrain.py#L247-L249

like here!

2022-06-13 19:15 UTC, tathey1 commented on brainlit/feature_extraction/base.py
> +    ) -> None:
cool lets keep it then

2022-06-13 19:16 UTC, tathey1 approved these changes
looks good

2022-06-13 19:16 UTC, merged