Code for axon mapping paper
neurodata/brainlit pull request #364
Opened 2022-08-29 21:02 UTC by tathey1

2022-08-31 18:27 UTC, tathey1 commented
@JacopoTeneggi review whatever you have time/energy for, no pressure. Even if you only verify that the files/code changed roughly matches the bullet points in my PR description, that would be much appreciated. Note: codecov went down because I removed some files that had above average coverage.

2022-09-01 02:00 UTC, JacopoTeneggi requested changes

2022-09-01 02:00 UTC, JacopoTeneggi commented on brainlit/map_neurons/map_neurons.py
> +def transform_GeometricGraph(
lowercase name of function

```suggestion
def transform_geometricgraph(
```

2022-09-01 02:00 UTC, JacopoTeneggi commented on brainlit/map_neurons/map_neurons.py
> +    - For a sequence of points, the finite-difference method from Svndquist & Veronis 1970 for nonuniform intervals is used.
If possible, include ref or title of paper

2022-09-01 02:00 UTC, JacopoTeneggi commented on docs/reference/map_neurons.rst
> +Mapping Neurons
- Add `similaritymeasures` as a dependency
- Add `statannotations` / `statannot` as a dependency
- Notebook fails on `Figure 4b,c,d) CloudReg + Real Neuron with error ```Unable to open file ... brainlit/experiments/register_axons/data/mapping-files/downloop_1_v.mat'```

2022-09-01 14:26 UTC, tathey1 commented on brainlit/map_neurons/map_neurons.py
> +def transform_GeometricGraph(
changed

2022-09-01 14:27 UTC, tathey1 commented on brainlit/map_neurons/map_neurons.py
> +    - For a sequence of points, the finite-difference method from Svndquist & Veronis 1970 for nonuniform intervals is used.
APA ref added (not sure if I need to add italics or something?)

2022-09-01 14:27 UTC, tathey1 commented on docs/reference/map_neurons.rst
> +Mapping Neurons
added dependencies to `setup.py`. Also added data file with git lfs and documentation to unzip the file before running notebook.

2022-09-01 14:34 UTC, JacopoTeneggi approved these changes

2022-09-01 14:40 UTC, merged